name: Ruby

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - run: bundle install
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - run: docker-compose run web bundle exec rake db:test:prepare
    - name: MiniTest
      run: docker-compose exec web rails test
    - run: docker-compose down
