name: Ruby

on: [push]

defaults:
  run:
    working-directory: ./server

jobs:
  minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install --yes libpq-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0

      - name: Set up gems cache
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-
      - name: Set up node_modules cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Install Node dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Set up database
        run: bundle exec rake db:setup

      - name: Run tests
        run: bundle exec rake test
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Set up gems cache
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --without default development test --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop --parallel
